name: Publish to NPM and Release To Github

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn publish:packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  release-github:
    name: Release To Github
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: release ${{ github.ref }}
